### Добавляет json анкету в монгу
POST http://{{host}}/{{add_route}}
Content-Type: application/json

{
  "id": 1,
  "name": "Sample",
  "content": {
    "glossary": {
      "title": "example glossary",
      "GlossDiv": {
        "title": "S",
        "GlossList": {
          "GlossEntry": {
            "ID": "SGML",
            "SortAs": "SGML",
            "GlossTerm": "Standard Generalized Markup Language",
            "Acronym": "SGML",
            "Abbrev": "ISO 8879:1986",
            "GlossDef": {
              "para": "A meta-markup language, used to create markup languages such as DocBook.",
              "GlossSeeAlso": ["GML", "XML"]
            },
            "GlossSee": "markup"
          }
        }
      }
    }
  }
}

### Запрос за опросником через ID
GET http://{{host}}/{{get_by_id}}/1