FROM node:alpine AS builder
RUN npm install -g http-server
WORKDIR /code
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /code /var/www
COPY --from=builder ./code/nginx.conf /etc/nginx/nginx.conf
EXPOSE 3001
ENTRYPOINT ["nginx","-g","daemon off;"]