### Отправка уведомлении пользователю
POST http://{{host}}/notify
Content-Type: application/json

{"medium": "whatsapp", "to": "+77783693745", "message": "Салам чертилы"}

### Запрос за опросником через ID
GET http://{{host}}/{{get_by_id}}/1


### Получение рекомендации по заболеваниям
POST http://{{host}}{{get_recommendation}}
Content-Type: application/json

{"answers": {"84": ["ASDASDADS", "ASDASDASDASD"],"1":["50"],"2":["Женский"],"3":["172"],"4":["100"],"5":["Да"],"6":["Диабет второго типа ","Онкология ","Имешическая болезнь сердца","Аутоиммунные заболевания"],"7":["Да"],"8":["Онкология ","Имешическая болезнь сердца","Повышенное давление (гипертензия)","Я не знаю или у них не было и нет хронических заболеваний"],"9":["Нет"],"11":["Да"],"12":["> 11.1"],"13":["Да"],"14":["115 - 155"],"15":["Не знаю "],"16":["Да"],"17":["> 12"],"18":["Нет"],"20":[],"21":["Да"],"22":["5 - 9"],"23":["В основном сидячий, малоподвижный "]}}

### Добавление заболевания в монгу
POST http://{{host}}{{add_disease}}
Content-Type: application/json

{
  "name": "Рак молочных желез",
  "tests": ["Маммография (каждые 2 года)", "УЗИ молочных желез"],
  "importance": "Рак молочных желез - самый распространенный вид рака среди женщин. 1 из 8 женщин развеет это заболевание. Ранняя диагностика увеличивает выживаемость до 92%.",
  "recommendations": ["Самообследование молочной железы, Визуальный осмотр кожи и соска каждый месяц с 40 лет", "Обследование молочной железы, Визуальный осмотр кожи и соска врачом терапевтом/ маммологом раз в два года с 40 лет"],
  "conditions": {"1":{"value": ["50"], "type": "integer", "compare": "greater"},"2":{"value": ["Женский"], "type": "string", "compare": "exact"}}
}

### Получение всех заболевании
GET http://{{host}}{{get_all_diseases}}
Content-Type: application/json

### Добавляет json анкету в монгу
POST http://{{host}}/{{add_route}}
Content-Type: application/json

{"questionnaire":  {
  "logoPosition": "right",
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "text",
          "name": "question1",
          "title": "Сколько вам лет? ",
          "inputType": "number",
          "min": 18,
          "max": 99,
          "step": 0
        },
        {
          "type": "checkbox",
          "name": "question2",
          "title": "Ваш пол ",
          "choices": [
            "Женский",
            "Мужской"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "text",
          "name": "question3",
          "title": "Ваш рост",
          "description": "В сантиметрах",
          "inputType": "number",
          "min": 100,
          "max": 220
        },
        {
          "type": "text",
          "name": "question4",
          "title": "Ваш вес ",
          "description": "В килограммах",
          "inputType": "number",
          "min": 20,
          "max": 220
        },
        {
          "type": "checkbox",
          "name": "question5",
          "title": "У вас есть хроническое заболевание? ",
          "description": "Например: диабет, заболевания сердца, кожи, легких, почек,  повышенное давление и другие ",
          "choices": [
            "Да",
            "Нет"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question6",
          "visibleIf": "{question5} = ['Да']",
          "title": "Отметьте какие хронические заболевания есть или были",
          "description": "Отметьте текущие и прошлые хронические заболевания",
          "choices": [
            "Повышенное давление (гипертензия)",
            "Диабет второго типа ",
            "Онкология ",
            "Имешическая болезнь сердца",
            "Аутоиммунные заболевания",
            "Гепатит В ",
            "Гепатит С ",
            "Заболевание почек ",
            "У меня нет и не было хронических заболевание"
          ],
          "otherText": "Другие (напишите) ",
          "maxSelectedChoices": 7,
          "selectAllText": "Все "
        },
        {
          "type": "checkbox",
          "name": "question7",
          "title": "Есть ли хронические заболевания у ваших близких родственников? ",
          "description": "У бабушки/дедушки, мама/папа, братья/сестры",
          "choices": [
            "Да",
            "Нет"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question8",
          "visibleIf": "{question7} = ['Да']",
          "title": "Если да, то отметьте какие есть или были у них хронические заболевания",
          "choices": [
            "Повышенное давление (гипертензия)",
            "Диабет второго типа ",
            "Онкология ",
            "Имешическая болезнь сердца",
            "Аутоиммунные заболевания",
            "Заболевание почек ",
            "Я не знаю или у них не было и нет хронических заболеваний"
          ],
          "otherText": "Другие (напишите) ",
          "maxSelectedChoices": 7
        },
        {
          "type": "checkbox",
          "name": "question9",
          "title": "Вы знаете свое рабочее артериальное давление?  ",
          "description": "Систолическое ",
          "choices": [
            "Да",
            "Нет"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question10",
          "visibleIf": "{question9} = ['Да']",
          "title": "Укажите в какое значение относится ваше систолическое давление (первое значение)",
          "description": "К примеру если у вас 120/80, укажите только 120 в 100-129",
          "choices": [
            "<100",
            "100-129",
            "130-139",
            "140-149",
            "150-159",
            ">160",
            "Я не знаю  "
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question11",
          "title": "Вы знаете свой уровень сахара в крови натощак?",
          "description": "Анализ глюкозы в лабораторных анализах",
          "choices": [
            "Да",
            "Нет"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question12",
          "visibleIf": "{question11} = ['Да']",
          "title": "Укажите ваш уровень глюкозы в крови ",
          "description": "В ммол/л",
          "choices": [
            "< 7.8 ",
            "7.8 – 11.1",
            "> 11.1",
            "Я не знаю "
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question13",
          "title": "Вы знаете свой уровень гемоглобина?",
          "choices": [
            "Да",
            "Нет"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question14",
          "visibleIf": "{question13} = ['Да'] and {question2} = ['Женский']",
          "title": "Укажите свой уровень гемоглобина в крови",
          "description": "В г/л (х10*9/л)",
          "choices": [
            "< 115",
            "115 - 155",
            "> 155",
            "Не знаю "
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question25",
          "visibleIf": "{question2} = ['Мужской'] and {question13} = ['Да']",
          "title": "Укажите свой уровень гемоглобина в крови",
          "description": "В г/л (х10*9/л)",
          "choices": [
            "< 135",
            "135 - 180",
            "> 180",
            "Не знаю "
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question15",
          "title": "Вы употребляете алкоголь? ",
          "choices": [
            "Да",
            "Нет"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question16",
          "visibleIf": "{question15} = ['Да']",
          "title": "Вы знаете сколько в среднем в неделю вы употребляете алкоголь? ",
          "description": "1 пиво 500 мл - 2 единицы, 1 стакан вина - 1 единица, 40 грамм водки - 1 единица",
          "choices": [
            "< 8",
            "8 - 12",
            "> 12"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question17",
          "title": "Вы курите? ",
          "choices": [
            "Да",
            "Нет"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question18",
          "visibleIf": "{question17} = ['Да']",
          "title": "Сколько сигарет в день вы курите? ",
          "choices": [
            "< 5",
            " 5 - 9",
            "10 - 19",
            "> 20"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question19",
          "visibleIf": "{question17} = ['Да']",
          "title": "Сколько вы курите?",
          "choices": [
            "< 1",
            "1 - 4",
            "5 - 9",
            "> 10"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question20",
          "title": "Вы раньше курили на постоянной основе? ",
          "choices": [
            "Да",
            "Нет"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question21",
          "visibleIf": "{question20} = ['Да']",
          "title": "Как долго вы курили перед тем как бросить курить?",
          "description": "В лет ",
          "choices": [
            "< 1 года",
            "1 - 4",
            "5 - 9",
            "> 10"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question22",
          "title": "Ваш уровень физической активности?",
          "choices": [
            "Прогулка",
            "Активный спорт",
            "В основном сидячий, малоподвижный "
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question23",
          "title": "Ваш рацион питания? ",
          "choices": [
            "Полезный (больше фруктов и овощей)",
            "Вредный (больше мяса и жирного)"
          ],
          "maxSelectedChoices": 1
        },
        {
          "type": "checkbox",
          "name": "question24",
          "title": "У вас есть следующие общие жалобы? Отметьте которые есть ",
          "choices": [
            "Усталость",
            "Быстрая Утомляемость",
            "Потеря веса",
            "Набор веса",
            "Потеря аппетита",
            "Повышенная Температура > 37.0С",
            "Озноб",
            "Ночные потения"
          ],
          "hasOther": true,
          "hasNone": true,
          "noneText": "Нет ",
          "otherText": "Другие (опишите) ",
          "maxSelectedChoices": 8
        }
      ],
      "title": "Базовый опросник",
      "description": "Первые 10 вопросов"
    }
  ]
}
}