IP = "0.0.0.0"
Port = ":8080"
Debug = true
MongoDatabaseName = "symptom"
StaticPath = "./frontend/dist"

[notificator]
    [notificator.WhatsApp]
        SID = "AC42b9427f004ea29ac1311e68dbc47fb5"
        Token = "76581fcaedc70cce3fea2af38408080a"

[database]
    [database.MongoDB]
        Username = "saubolkz"
        Password = "1Nxow6yFyvxHeyN3"
        Host = "cluster0.nvdhx.mongodb.net"
        Timeout = 2
    [database.MySQL]
        User = "root"
        Password = "Project_mysql#65"
        Host = "localhost"
        Port = "3306"
        Database = "test"

[collections]
    [collections.questionnaire]
        Name = "questionnaire"
    [collections.diseases]
        Name = "diseases"
    [collections.answers]
        Name = "answers"